# Generated by Django 2.2 on 2020-04-19 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liks', to='webapp.Image', verbose_name='Фото'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('photo', 'author')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
